# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # Specify that Dependabot should check for GitHub Actions updates
    directory: ".github/workflows/" # Location of the GitHub Actions workflow files
    schedule:
      interval: "weekly" # Check for updates on a weekly basis

  # Update Python dependencies
  - package-ecosystem: "pip"
    directory: "/"  # Location of your requirements.txt file
    schedule:
      interval: "weekly"
