#########################################
DiagMCMC:
  ExcludedTypes: ["ndd_", "skd_joint_"]
  ExcludedNames: ["b_"]
  nBatches: 20
  nLags: 25000
  PlotRelativeToPrior: "false"


#########################################
GetPenaltyTerm:
  PenaltySets: ["Flux", "ND_Syst", "Xsec", "CCQE_Eb"]

  #KS: Goes as vector with names based on which we select, true or false whether we want to be inclusive or exclusive and fancy name
  Flux:
    - ["b_"]
    - false
    - "-logL_{Flux}"
  ND_Syst:
    - ["NDS_"]
    - false
    - "-logL_{ND_Syst}"
  Xsec:
    - ["b_", "NDS_"]
    #KS: For Xsec we take parameter which isn't flux or detector this is what true means here
    - true
    - "-logL_{Cross-Section}"

  CCQE_Eb:
    - ["EB_dial_", "Alpha_q3"]
    - false
    - "-logL_{CCQE Eb}"


#########################################
ProcessMCMC:
  #Select which parameters blocks to reject for example ND and FD detector, look for starting string
  ExcludedTypes: ["ndd_", "skd_joint_"]
  #Select which parameter names to remove, for example all flux, look for starting string
  ExcludedNames: ["b_"]
  #AdditionalCuts
  Posterior1DCut: ""
  #Posterior1DCut: "delm2_23 > 0"

  #Basic settings
  PlotRelativeToPrior: false
  PrintToPDF: true
  #if false it will not plot error band for parameters with flat prior
  PlotErrorForFlatPrior: true
  FancyNames: true
  PlotBinValue: false

  #Correlation related
  Smoothing: true

  #Functionality 1D
  MakeCredibleIntervals: true
  CalcBayesFactor: true
  CalcSavageDickey: true
  CalcBipolarPlot: false

  #Functionality 2D
  PlotCorr: false
  MakeSubOptimality: ["false", 100]
  MakeViolin: true
  MakeCredibleRegions: false
  GetTrianglePlot: true
  #Perform some covariance stability test
  DiagnoseCovarianceMatrix: false
  # Assign weight to each mcmc step according to new prior
  ReweightPrior: false
  #Perform Kolmogorov Smirnov test, only works when at least two files are being processed
  PerformKStest: true

  #KS: Credible Intervals/Regions Cosmetic, code has default values so even if you don't pass anything still code will produce fancy plots :)
  CredibleIntervals: [0.99, 0.90, 0.68]
  #In case of sigma, please set CredibleInSigmas to true first
  #CredibleIntervals: [3, 2, 1]
  #kCyan+4, kCyan-2, kCyan-10
  CredibleIntervalsColours: [436, 430, 422]

  #If true Credible intervals should be in percentage
  CredibleInSigmas: false
  CredibleRegions: [0.99, 0.90, 0.68]
  #In case of sigma, please set CredibleInSigmas to true first
  #CredibleRegions: [3, 2, 1]
  # kDashed, kSolid, kDotted
  CredibleRegionStyle: [2, 1, 3]
  #kGreen-3, kGreen-10, kGreen
  CredibleRegionColor: [413, 406, 416]

  #KS: Plot only 2D posteriors with correlations greater than 0.2
  Post2DPlotThreshold: 0.2

  # Used for diagnostic covariance matrix
  NIntervals: 5

  BayesFactor:
    # Goes as follows: ParamName Name[Model 1, Model 2], Model1[lower, upper ], Model2[lower, upper ]
    - ["RS_Delta_Decay", ["Isotropic", "Delta Like"], [0, 0.5], [0.5, 1]]
    - ["PNNN_Shape", ["NN Only", "PN Only"], [-1, 0], [0, 1]]
    - ["delm2_23", ["IH", "NH"], [-0.01, 0], [0, 0.01]]
    - ["sin2th_23", ["LO", "UO"], [0, 0.5], [0.5, 1]]

  SavageDickey:
    - ["RS_Delta_Decay", 0.9999, [0, 1]]
    - ["Alpha_q3", 0.0001, [0, 1]]
    - ["MAQE", 1.13, [0, 0]]  # Last array doesn't matter as parameter has Gaussian
    - ["EB_dial_C_nu", 12, [0, 0]]

  BipolarPlot:
    - ["RS_Delta_Decay", [0, 1]]

    #KS: Feel free to pass whatever combination you like
  TrianglePlot:
    - ["CCQE", ["MAQE", "Pauli_Blocking_C_nu", "Optical_Potential_C", "EB_dial_C_nu"]]
    - ["SPP", ["CA5", "MARES", "ISO_BKG"]]
    - ["PauliOptical", ["Pauli_Blocking_C_nu", "Pauli_Blocking_O_nu", "Pauli_Blocking_C_nubar", "Pauli_Blocking_O_nubar", "Optical_Potential_C", "Optical_Potential_O"]]
    - ["CCQE_Eb", ["EB_dial_C_nu", "EB_dial_O_nu", "EB_dial_C_nubar", "EB_dial_O_nubar", "Alpha_q3"]]
    - ["Oscillation", ["delta_cp", "delm2_23", "sin2th_13", "sin2th_23"]]

  #First param name, then new prior and new prior error
  # apply reactor constraints [vector of param names] [vector of new central value] [vector of new prior errors]
  PriorReweighting: [ ["sin2th_13"], [0.0220], [0.0007] ]
  #Fancy example, not physics motivated but to show funcionality
  #PriorReweighting: [ ["MAQE", "Pauli_Blocking_C_nu"], [1.05, 0.1], [ 0.04, 0.5] ]

#########################################
GetPostfitParamPlots:
  ## groups of parameters to plot together
  paramGroups: [
        "CCQE",
        "2p2h",
        "SPP",
        "RES_EB",
        "FSI",
        "XSecMisc",
        "CCQE_EB",

        #"ND_EcalTrackEff_Mu_DS",
        #"ND_EcalTrackEff_Mu_Barrel",
        #"ND_EcalTrackEff_e_DS",
        #"ND_EcalTrackEff_e_Barrel",

        #"ND_OOFV_Tracker",
        #"ND_OOFV_Rate",
        #"ND_OOFV_Reco",

        #"ND_Pileup",
        #"ND_ECalPhotonPileUp",

        #"ND_ECalEmHipPID",
        "ND_Sand",
        "ND_SI",
        "ND_FGDMass",
        "ND_FGDTrackEff",
        "ND_Other",
    ]

    ## define the groups of parameters, should go <block name> = [<plot title>, [<ylim low>, <ylim up>], ["ParamName1", "ParamName2" ...]
  CCQE: ["CCQE", [-1.0, 3.0],
          ["MAQE", "Q2_norm_5", "Q2_norm_6", "Q2_norm_7", "PShell_MF_Norm_C", "SShell_MF_Norm_C",
          "SRC_Norm_C", "PShell_MF_PMissShape_C", "SShell_MF_PMissShape_C", "P1_2Shell_MF_Norm_O",
          "P3_2Shell_MF_Norm_O", "SShell_MF_Norm_O", "SRC_Norm_O", "P1_2Shell_MF_PMissShape_O", "P3_2Shell_MF_PMissShape_O",
          "SShell_MF_PMissShape_O", "Pauli_Blocking_C_nu", "Pauli_Blocking_O_nu", "Pauli_Blocking_C_nubar", "Pauli_Blocking_O_nubar"]]

  2p2h: ["2p2h", [-1.5, 2.5],
          ["2p2h_norm_nu", "2p2h_norm_nubar", "2p2h_normCtoO", "2p2h_Edep_lowEnu", "2p2h_Edep_highEnu", "2p2h_Edep_lowEnubar",
          "2p2h_Edep_highEnubar", "PNNN_Shape", "2p2h_shape_C_np", "2p2h_shape_C_NN", "2p2h_shape_O_np", "2p2h_shape_O_NN"]]

  SPP: ["SPP",  [-0.1, 2.8],
          ["CA5", "MARES", "ISO_BKG_LowPPi", "ISO_BKG", "RS_Delta_Decay", "SPP_Pi0Norm_numu", "SPP_Pi0Norm_numubar"]]

  RES_EB: ["RES Binding Energy", [-8.0, 60.0],
            ["RES_Eb_C_numu", "RES_Eb_O_numu", "RES_Eb_C_numubar", "RES_Eb_O_numubar"]]

  FSI: ["FSI", [-0.5, 2.8],
          ["FEFQE", "FEFQEH", "FEFINEL", "FEFABS", "FEFCX", "FEFCXH", "NucleonFSI_Scattering", "NucleonFSI_SPP"]]

  XSecMisc: ["CC DIS, CC Multi #pi, CC coh., NC, #nu_{e}", [-1.5, 2.5],
              ["CC_Coh_C", "CC_Coh_O", "MPi_Multi_TotXSec", "MPi_BY_Vector", "MPi_BY_Axial", "MPi_Multi_Shape",
                "CC_BY_DIS", "CC_DIS_MultPi_Norm_Nu", "CC_DIS_MultPi_Norm_Nubar", "CC_Misc", "NC_Coh", "NC_1gamma",
                "NC_other_near", "NC_other_far", "CC_norm_nu", "CC_norm_nubar", "nue_numu", "nuebar_numubar"]]

  CCQE_EB: ["CCQE Binding Energy", [-10.0, 18.0],
              ["EB_dial_C_nu", "EB_dial_C_nubar", "EB_dial_O_nu", "EB_dial_O_nubar", "Alpha_q3"]]

  ND_EcalTrackEff_Mu_DS: ["ECal Tracking Efficiency - #mu Downstream", [-2.0, 2.0], ["NDS_ECalTrackEff_0", "NDS_ECalTrackEff_1", "NDS_ECalTrackEff_2",
                      "NDS_ECalTrackEff_3", "NDS_ECalTrackEff_4", "NDS_ECalTrackEff_5", "NDS_ECalTrackEff_6"]]

  ND_EcalTrackEff_Mu_Barrel: ["ECal Tracking Efficiency - #mu Barrel", [-2.0, 2.0], ["NDS_ECalTrackEff_7", "NDS_ECalTrackEff_8", "NDS_ECalTrackEff_9",
                      "NDS_ECalTrackEff_10", "NDS_ECalTrackEff_11", "NDS_ECalTrackEff_12", "NDS_ECalTrackEff_13"]]

  ND_EcalTrackEff_e_DS: ["ECal Tracking Efficiency - e Downstream", [-2.0, 2.0], ["NDS_ECalTrackEff_14", "NDS_ECalTrackEff_15", "NDS_ECalTrackEff_16",
                      "NDS_ECalTrackEff_17", "NDS_ECalTrackEff_18", "NDS_ECalTrackEff_19"]]

  ND_EcalTrackEff_e_Barrel: ["ECal Tracking Efficiency - e Barrel", [-2.0, 2.0], ["NDS_ECalTrackEff_20", "NDS_ECalTrackEff_21", "NDS_ECalTrackEff_22",
                      "NDS_ECalTrackEff_23", "NDS_ECalTrackEff_24", "NDS_ECalTrackEff_25"]]

  ND_OOFV_Tracker: ["Out of Fiducial Volume", [-2.0, 2.0], ["NDS_OOFV_0", "NDS_OOFV_1", "NDS_OOFV_2"]]

  ND_OOFV_Rate: ["OOFV - Rate", [-2.0, 2.0], ["NDS_OOFV_3", "NDS_OOFV_4", "NDS_OOFV_5", "NDS_OOFV_6", "NDS_OOFV_7", "NDS_OOFV_8", "NDS_OOFV_9", "NDS_OOFV_10",
                  "NDS_OOFV_11", "NDS_OOFV_12", "NDS_OOFV_13", "NDS_OOFV_14"]]

  ND_OOFV_Reco: ["OOFV - Reconstruction", [-2.0, 2.0], ["NDS_OOFV_15", "NDS_OOFV_16", "NDS_OOFV_17", "NDS_OOFV_18", "NDS_OOFV_19"]]

  ND_ECalEmHipPID: ["ECal EM HIP PID", [-2.0, 2.0], ["NDS_ECalEmHipPID_0", "NDS_ECalEmHipPID_1", "NDS_ECalEmHipPID_2", "NDS_ECalEmHipPID_3",
                      "NDS_ECalEmHipPID_4", "NDS_ECalEmHipPID_5"]]

  ND_Pileup: ["Pile Up", [-2.0, 2.0], ["NDS_PileUp_FHC", "NDS_PileUp_RHC"]]

  ND_ECalPhotonPileUp: ["ECal Photon Pileup", [-2.0, 2.0], ["NDS_ECalPhotonPileUp_0", "NDS_ECalPhotonPileUp_1", "NDS_ECalPhotonPileUp_2",
                "NDS_ECalPhotonPileUp_3", "NDS_ECalPhotonPileUp_4"]]

  ND_Sand: ["Sand", [-2.0, 2.0], ["NDS_SandMu_RHC", "NDS_SandMu_FHC"]]

  ND_SI: ["Secondary Interaction", [-2.0, 2.0], ["NDS_SIPion_Abs", "NDS_SIPion_CEX", "NDS_SIPion_QE", "NDS_SIProton"]]

  ND_FGDMass: ["FGD Mass", [-2.0, 2.0], ["NDS_FgdMass_scint", "NDS_FgdMass_water"]]

  ND_FGDTrackEff: ["FGD Tracking Efficiency", [-2.0, 2.0], ["NDS_FgdHybridTrackEff_FGD1FHCPion", "NDS_FgdHybridTrackEff_FGD1FHCProton",
                    "NDS_FgdHybridTrackEff_FGD2FHCPion", "NDS_FgdHybridTrackEff_FGD2FHCProton", "NDS_FgdHybridTrackEff_FGD1RHCPion",
                    "NDS_FgdHybridTrackEff_FGD1RHCProton", "NDS_FgdHybridTrackEff_FGD2RHCPion", "NDS_FgdHybridTrackEff_FGD2RHCProton"]]

  ND_Other: ["Near Detector - Other Efficiencise", [-2.0, 2.0], ["NDS_ChargeIDEff", "NDS_TpcClusterEff", "NDS_TpcTrackEff", "NDS_TpcFgdMatchEff", "NDS_MichelEleEff", ]]

  ##EM: groups of flux parameters to be plotted together
  FluxGroups: [
        "ND280_FHC_numu",
        "ND280_FHC_numubar",
        "ND280_FHC_nue",
        "ND280_FHC_nuebar",
        "ND280_RHC_numu",
        "ND280_RHC_numubar",
        "ND280_RHC_nue",
        "ND280_RHC_nuebar",
        "SK_FHC_numu",
        "SK_FHC_numubar",
        "SK_FHC_nue",
        "SK_FHC_nuebar",
        "SK_RHC_numu",
        "SK_RHC_numubar",
        "SK_RHC_nue",
        "SK_RHC_nuebar"
    ]

  ##EM: define the groups of flux parameters, it goes groupName = [<Plot title>, <binning name>, [<param ID low>, <param ID high>]]
  ND280_FHC_numu: ["ND280 FHC #nu_{#mu}",          [0.7, 1.3], "SameSignMu",  [0, 10]]
  ND280_FHC_numubar: ["ND280 FHC #bar{#nu}_{#mu}", [0.7, 1.3], "WrongSignMu", [11, 15]]
  ND280_FHC_nue: ["ND280 FHC #nu_{e}",             [0.7, 1.3], "SameSignE",   [16, 22]]
  ND280_FHC_nuebar: ["ND280 FHC #bar{#nu}_{e}",    [0.7, 1.3], "WrongSignE",  [23, 24]]

  ND280_RHC_numu: ["ND280 RHC #nu_{#mu}",          [0.7, 1.3], "WrongSignMu", [25, 29]]
  ND280_RHC_numubar: ["ND280 RHC #bar{#nu}_{#mu}", [0.7, 1.3], "SameSignMu",  [30, 40]]
  ND280_RHC_nue: ["ND280 RHC #nu_{e}",             [0.7, 1.3], "WrongSignE",  [41, 42]]
  ND280_RHC_nuebar: ["ND280 RHC #bar{#nu}_{e}",    [0.7, 1.3], "SameSignE",   [43, 49]]

  SK_FHC_numu: ["SK FHC #nu_{#mu}",          [0.7, 1.3], "SameSignMu",  [50, 60]]
  SK_FHC_numubar: ["SK FHC #bar{#nu}_{#mu}", [0.7, 1.3], "WrongSignMu", [61, 65]]
  SK_FHC_nue: ["SK FHC #nu_{e}",             [0.7, 1.3], "SameSignE",   [66, 72]]
  SK_FHC_nuebar: ["SK FHC #bar{#nu}_{e}",    [0.7, 1.3], "WrongSignE",  [73, 74]]

  SK_RHC_numu: ["SK RHC #nu_{#mu}",          [0.7, 1.3], "WrongSignMu", [75, 79]]
  SK_RHC_numubar: ["SK RHC #bar{#nu}_{#mu}", [0.7, 1.3], "SameSignMu",  [80, 90]]
  SK_RHC_nue: ["SK RHC #nu_{e}",             [0.7, 1.3], "WrongSignE",  [91, 92]]
  SK_RHC_nuebar: ["SK RHC #bar{#nu}_{e}",    [0.7, 1.3], "SameSignE",   [93, 99]]

  ## the energy binning's to be used for flux plots
  FluxBinning:
    SameSignMu: [0.3, 0.4, 0.5, 0.6, 0.7, 1.0, 1.5, 2.5, 3.5, 5.0, 7.0, 30.0]
    SameSignE:  [0.3, 0.5, 0.7, 0.8, 1.5, 2.5, 4.0, 30.0]
    WrongSignMu: [0.3, 0.7, 1.0, 1.5, 2.5, 30.0]
    WrongSignE: [0.3, 2.5, 30.0]



  ##  EM: Will make this  configurable
  ## define prettier names for parameters to use in e.g. plot
  PrettyNames:
    MAQE: "M_{A}^{QE}"

    Q2_norm_0: "Q^{2} Norm 0"
    Q2_norm_1: "Q^{2} Norm 1"
    Q2_norm_2: "Q^{2} Norm 2"
    Q2_norm_3: "Q^{2} Norm 3"
    Q2_norm_4: "Q^{2} Norm 4"
    Q2_norm_5: "High Q^{2} Norm 1"
    Q2_norm_6: "High Q^{2} Norm 2"
    Q2_norm_7: "High Q^{2} Norm 3"

    PShell_MF_Norm_C: "P Shell MF Norm ^{12}C"
    SShell_MF_Norm_C: "S Shell MF Norm ^{12}C"
    SRC_Norm_C: "SRC Norm ^{12}C"
    PShell_MF_PMissShape_C: "P Shell MF P_{Miss} ^{12}C"
    SShell_MF_PMissShape_C: "S Shell MF P_{Miss} ^{12}C"
    P1_2Shell_MF_Norm_O: "P_{1/2} Shell MF Norm ^{16}O"
    P3_2Shell_MF_Norm_O: "P_{3/2} Shell MF Norm ^{16}O"
    SShell_MF_Norm_O: "S Shell MF Norm ^{16}O"
    SRC_Norm_O: "SRC Norm ^{16}O"
    P1_2Shell_MF_PMissShape_O: "P_{1/2} Shell MF P_{Miss} ^{16}O"
    P3_2Shell_MF_PMissShape_O: "P_{3/2} Shell MF P_{Miss} ^{16}O"
    SShell_MF_PMissShape_O: "S Shell MF P_{Miss}^{16}O"

    Pauli_Blocking_C_nu: "Pauli Blocking ^{12}C #nu"
    Pauli_Blocking_O_nu: "Pauli Blocking ^{16}O #nu"
    Pauli_Blocking_C_nubar: "Pauli Blocking ^{12}C #bar{#nu}"
    Pauli_Blocking_O_nubar: "Pauli Blocking ^{16}O #bar{#nu}"
    Optical_Potential_C: "Optical Potential ^{12}C"
    Optical_Potential_O: "Optical Potential ^{16}O"

    ## now 2p2h params
    "2p2h_norm_nu": "2p2h Norm #nu"
    "2p2h_norm_nubar": "2p2h Norm #bar{#nu}"
    "2p2h_normCtoO": "2p2h Norm ^{12}C/^{16}O"

    "2p2h_Edep_lowEnu": "2p2h Edep Low #nu"
    "2p2h_Edep_highEnu": "2p2h Edep High #nu"
    "2p2h_Edep_lowEnubar": "2p2h Edep Low #bar{#nu}"
    "2p2h_Edep_highEnubar": "2p2h Edep High #bar{#nu}"

    PNNN_Shape: "PNNN Shape"
    "2p2h_shape_C_np": "2p2h shape ^{12}C np"
    "2p2h_shape_O_np": "2p2h shape ^{16}O np"
    "2p2h_shape_C_NN": "2p2h shape ^{12}C nn"
    "2p2h_shape_O_NN": "2p2h shape ^{16}O nn"
    "2p2h_shape_C": "2p2h shape ^{12}C"
    "2p2h_shape_O": "2p2h shape ^{16}O"

    ## Now SPP
    CA5: "C_{5}^{A}"
    MARES: "M_{A}^{RES}"
    ISO_BKG: "Non-res I_{1/2}"
    ISO_BKG_LowPPi: "Non-res I_{1/2} Low p_{#pi}"

    RES_Eb_C_numu: "RES E_{b} ^{12}C #nu_{#mu}"
    RES_Eb_O_numu: "RES E_{b} ^{16}O #nu_{#mu}"
    RES_Eb_C_numubar: "RES E_{b} ^{12}C #bar{#nu}_{#mu}"
    RES_Eb_O_numubar: "RES E_{b} ^{16}O #bar{#nu}_{#mu}"

    RS_Delta_Decay: "RS #Delta Decay"
    SPP_Pi0Norm_numu: "SPP #pi^{0} Norm #nu_{#mu}"
    SPP_Pi0Norm_numubar: "SPP #pi^{0} Norm #bar{#nu}_{#mu}"

    FEFQE: "#pi FSI QE low E"
    FEFQEH: "#pi FSI QE high E"
    FEFINEL: "#pi FSI Prod."
    FEFABS: "#pi FSI Abs."
    FEFCX: "#pi FSI Cex low E"
    FEFCXH: "#pi FSI Cex high E"
    Nucleon_FSI: "Nucleon FSI"

    CC_Coh_C: "CC coh. ^{12}C"
    CC_Coh_O: "CC coh. ^{16}O"

    MPi_Multi_TotXSec: "M#pi  Multi TotXSec"
    MPi_BY_Vector: "M#pi  BY Vector"
    MPi_BY_Axial: "M#pi BY Axial"
    MPi_Multi_Shape: "M#pi Multi Shape"
    CC_BY_DIS: "CC BY DIS"
    CC_DIS_MultPi_Norm_Nu: "CC DIS/M#pi Norm #nu"
    CC_DIS_MultPi_Norm_Nubar: "CC DIS/M#pi Norm #bar{#nu}"

    CC_Misc: "CC Misc"

    CC_norm_nu: "CC Norm #nu"
    CC_norm_nubar: "CC Norm #bar{#nu}"
    nue_numu: "#nu_{e}/#nu_{#mu}"
    nuebar_numubar: "#bar{#nu}_{e}/#bar{#nu}_{#mu}"

    NC_Coh: "NC coh."
    NC_1gamma: "NC 1#gamma"
    NC_other_near: "NC oth. ND280"
    NC_other_far: "NC oth. SK"

    ## At the end hated by everyone CCQE Eb
    EB_dial_C_nu: "CCQE E_{b} ^{12}C #nu"
    EB_dial_C_nubar: "CCQE E_{b} ^{12}C #bar{#nu}"
    EB_dial_O_nu: "CCQE E_{b} ^{16}O #nu"
    EB_dial_O_nubar: "CCQE E_{b} ^{16}O #bar{#nu}"
    Alpha_q3: "#alpha correction (q_{3})"

    ## KS: Oscillation parameters, we don't use it right now but in future we could move this function to MCMC Processor and have some global tool for fancy plots
    delta_cp: "#delta_{CP}"
    delm2_23: "#Delta m^{2}_{23}"
    delm2_12: "#Delta m^{2}_{12}"
    sin2th_13: "sin^{2}(#theta_{13})"
    sin2th_23: "sin^{2}(#theta_{23})"
    sin2th_12: "sin^{2}(#theta_{12})"

    ## EM: Near detector systematic parameters
    NDS_OOFV_0: "Tracker 0"
    NDS_OOFV_1: "Tracker 1"
    NDS_OOFV_2: "Tracker 2"

    NDS_OOFV_3: "P0D FHC #nu_{#mu}"
    NDS_OOFV_4: "P0D RHC #nu_{#mu}"
    NDS_OOFV_5: "P0D RHC #bar{#nu}_{#mu}"

    NDS_OOFV_6: "ECal FHC #nu_{#mu}"
    NDS_OOFV_7: "ECal RHC #nu_{#mu}"
    NDS_OOFV_8: "ECal RHC #bar{#nu}_{#mu}"

    NDS_OOFV_9: "SMRD FHC #nu_{#mu}"
    NDS_OOFV_10: "SMRD RHC #nu_{#mu}"
    NDS_OOFV_11: "SMRD RHC #bar{#nu}_{#mu}"

    NDS_OOFV_12: "Other FHC #nu_{#mu}"
    NDS_OOFV_13: "Other RHC #nu_{#mu}"
    NDS_OOFV_14: "Other RHC #bar{#nu}_{#mu}"

    NDS_OOFV_15: "In Tracker - D/S"
    NDS_OOFV_16: "High Angle"
    NDS_OOFV_17: "Last Module Failure"
    NDS_OOFV_18: "Double Skipped Layer"
    NDS_OOFV_19: "Hard Scatter"

    NDS_ECalTrackEff_0: "0 - 50 MeV"
    NDS_ECalTrackEff_1: "50 - 100 MeV"
    NDS_ECalTrackEff_2: "100 - 150 MeV"
    NDS_ECalTrackEff_3: "150 - 250 MeV"
    NDS_ECalTrackEff_4: "250 - 400 MeV"
    NDS_ECalTrackEff_5: "400 - 700 MeV"
    NDS_ECalTrackEff_6: "> 700 MeV"
    NDS_ECalTrackEff_7: "0 - 100 MeV"
    NDS_ECalTrackEff_8: "100 - 150 MeV"
    NDS_ECalTrackEff_9: "150 - 200 MeV"
    NDS_ECalTrackEff_10: "200 - 250 MeV"
    NDS_ECalTrackEff_11: "250 - 400 MeV"
    NDS_ECalTrackEff_12: "400 - 700 MeV"
    NDS_ECalTrackEff_13: "> 700 MeV"
    NDS_ECalTrackEff_14: "0 - 300 MeV"
    NDS_ECalTrackEff_15: "300 - 450 MeV"
    NDS_ECalTrackEff_16: "450 - 600 MeV"
    NDS_ECalTrackEff_17: "600 - 900 MeV"
    NDS_ECalTrackEff_18: "900 - 3000 MeV"
    NDS_ECalTrackEff_19: "> 3000 MeV"
    NDS_ECalTrackEff_20: "0 - 300 MeV"
    NDS_ECalTrackEff_21: "300 - 450 MeV"
    NDS_ECalTrackEff_22: "450 - 600 MeV"
    NDS_ECalTrackEff_23: "600 - 900 MeV"
    NDS_ECalTrackEff_24: "900 - 2500 MeV"
    NDS_ECalTrackEff_25: "1500 - 3000 MeV"

    NDS_ECalEmHipPID_0: "e Downstream"
    NDS_ECalEmHipPID_1: "e Barrel"
    NDS_ECalEmHipPID_2: "#mu Downstream"
    NDS_ECalEmHipPID_3: "#mu Barrel"
    NDS_ECalEmHipPID_4: "#pi Downstream"
    NDS_ECalEmHipPID_5: "#pi Barrel"

    NDS_ECalPhotonPileUp_0: "0"
    NDS_ECalPhotonPileUp_1: "1"
    NDS_ECalPhotonPileUp_2: "2"
    NDS_ECalPhotonPileUp_3: "3"
    NDS_ECalPhotonPileUp_4: "4"
    NDS_ECalPhotonPileUp_5: "5"

    NDS_PileUp_FHC: "FHC"
    NDS_PileUp_RHC: "RHC"

    NDS_SandMu_FHC: "FHC"
    NDS_SandMu_RHC: "RHC"

    NDS_FgdMass_scint: "Scintillator"
    NDS_FgdMass_water: "Water"

    NDS_SIPion_CEX: "#pi CEX"
    NDS_SIPion_Abs: "#pi ABS"
    NDS_SIPion_QE: "#pi QE"
    NDS_SIProton: "proton"

    NDS_FgdHybridTrackEff_FGD1FHCPion: "FGD1 FHC #pi"
    NDS_FgdHybridTrackEff_FGD1FHCProton: "FGD1 FHC proton"
    NDS_FgdHybridTrackEff_FGD1RHCPion: "FGD1 RHC #pi"
    NDS_FgdHybridTrackEff_FGD1RHCProton: "FGD1 RHC proton"
    NDS_FgdHybridTrackEff_FGD2FHCPion: "FGD2 FHC #pi"
    NDS_FgdHybridTrackEff_FGD2FHCProton: "FGD2 FHC proton"
    NDS_FgdHybridTrackEff_FGD2RHCPion: "FGD2 RHC #pi"
    NDS_FgdHybridTrackEff_FGD2RHCProton: "FGD2 RHC proton"

    NDS_ChargeIDEff: "Charge ID"
    NDS_TpcClusterEff: "TPC Clustering"
    NDS_TpcTrackEff: "TPC Tracking"
    NDS_TpcFgdMatchEff: "TPC-FGD Match"
    NDS_MichelEleEff: "Michel Electron"
