ReweightMCMC:
  # Reactor constraint reweight
  ReactorConstraint:
    Enabled: true
    ReweightName: "PDG Reactor Constraint"
    ReweightDim: 1
    ReweightVar: "sin2th_13"
    ReweightType: "Gaussian"
    ReweightPrior: [0.0220, 0.0007] # [mean, sigma] for Gaussian
    
  # Combined theta13 and deltaCP constraint
  DayaBay2DConstraint:
    Enabled: true
    ReweightName: "DayaBay theta13-delm2_23 Constraint"
    ReweightDim: 2
    ReweightVar: ["delm2_23","sin2th_13"]
    ReweightType: "TGraph2D"
    ReweightPrior: 
      file: "/home/ppe/d/driley/DayaBay_new/MaCh3/utils/reweighting/reactor_constraint_2D/chi_sq_processing/DayaBay_2DConstraint.root"
      graph_name: "DayaBay_2DGraph"
      x_axis: "delm2_23"
      y_axis: "sin2th_13" 
      
